### ISSUE TITLE
Installation without mamba?

### ISSUE THREAD

**Issue by gcha31** [quadram-institute-bioscience/dadaist2#11]
Dear dadaist2 team,

I am trying to install dadaist2 in a conda environment. The computing cluster of my university does not allow installing 'mamba', so I skipped it and now trying to install dadaist2 directly:

```
conda create -n dadaist
conda activate dadaist
conda install -c bioconda dadaist2
```

However, I am at the 'solving environment' stage for more than 20 min. Is it possible to install it this way?

Best,
Gyuhyon

**Comment by telatin** [comment]
Hi there,
At the moment it's not possible without mamba, but mamba itself can be installed via conda, is that not possible?

Do you use containers (Docker or Singularity) in your cluster? That might be another option.

In any case we are releasing (~1 week or so) an alternative installation method that might work with conda

**Comment by gcha31** [comment]
Thank you for your response. I would look into if Docker of Singularity is available in my cluster.
Looking forward to seeing the alternative installation methods as well!

**Comment by telatin** [comment]
Could you please try this way?

```
wget "https://quadram-institute-bioscience.github.io/dadaist2/dadaist2-1.1.yaml"
conda create -n dadaist2 --file dadaist2-1.1.yaml
```

Note: missing "env" after conda

**Comment by telatin** [comment]
Hello @gcha31!
Did the `dadaist2-1.1.yaml` solution work for you? 
I would like to better support this installation format even making it the preferred way in the future.

**Comment by telatin** [comment]
Hi, I will support the `yaml` way and you will find updated instructions:
https://quadram-institute-bioscience.github.io/dadaist2/installation#install-via-conda-environment-files.

Please feel free to let me know if there are any issues
