### ISSUE TITLE
DADA2 Command Modifications

### ISSUE THREAD

**Issue by kellyshannon99** [quadram-institute-bioscience/dadaist2#13]
I am very interested in using this program, but I was wondering if you are able to customize any DADA2 commands within the wrapper (sorry in advance if this is stated in the documentation and I missed it). For example, if you wanted to modify the pooling option in the dada() core denoising command or change any parameters at the filtering step. I normally make these kinds of modifications via the RStudio DADA2 package, but are you only able to run it with default parameters with dadaist2? 

**Describe the solution you'd like**
If this isn't available already, being able to manually tweak any of the DADA2 command, like you can do when running the program on RStudio. 
 
**Additional context**
Here's an example of parameters that I have modified on RStudio, where singletons are maintained and pooling is set to pseudo: 

setDadaOpt(DETECT_SINGLETONS=TRUE)

dada_F_bp <- dada(derep_F_bp, err=errors_F, multithread=TRUE, pool = "pseudo")

Thank you in advance!

**Comment by telatin** [comment]
Hello and thanks for asking!
There are a set of parameters that can be already tweaked, and I will update the documentation to make this easier to do.

In addition to this, an independent wrapper to perform only the DADA2 denoising is also under development.

**Comment by kellyshannon99** [comment]
Fantastic, thank you for the quick reply!

**Comment by telatin** [comment]
In a future release all the setDadaOpt(...) options will be supported via configuration file, it will take some months to have it in production. Thanks for sharing your request!
