### ISSUE TITLE
Running dadaist without alignment/tree-building steps

### ISSUE THREAD

**Issue by padbc** [quadram-institute-bioscience/dadaist2#14]
Thank you for such a great tool. Question: I may have missed something obvious in the manual, but can the clustalo/tree inference steps be disabled?

**Comment by telatin** [comment]
Hi @padbc, thanks for the feedback.
At the moment there is no way to do so.

A redesign of the interface in ongoing, but in the meanwhile I can push an update to just skip these steps, but some downstream analyses might be impaired.

**Comment by padbc** [comment]
Great -- thank you. I'll close this for now.
