### ISSUE TITLE
Mamba install throws an error with missing packages

### ISSUE THREAD

**Issue by sudeep71** [quadram-institute-bioscience/dadaist2#19]
Hi, 
I am trying to install using mamba and run this software but I am having some trouble with the phlyloseq package and R. The packages seem to be present but I get an error. 

[13:14:24] Input directory "path_to/trial_reads/data/microbial/toy/example-output1/" created with Dadaist2 1.2.5                                  dadaist2-phyloseqMake:55
           MicrobiomeAnalyst directory found: path_to/data/microbial/toy/example-output1/MicrobiomeAnalyst                            dadaist2-phyloseqMake:56
ERROR: R script failed with exit code 1
R version 4.0.5 (2021-03-31) 
 * Input:  path_to/trial_reads/data/microbial/toy/example-output1/ 
Error: package or namespace load failed for ‘phyloseq’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object 'path_to/miniconda3/envs/dadaist/lib/R/library/rhdf5/libs/rhdf5.so':
  libcrypto.so.1.1: cannot open shared object file: No such file or directory
Execution halted

#################################################
#install
conda install -y -c conda-forge mamba
mamba install -y -c conda-forge -c bioconda dadaist2

dadaist2 --version
dadaist2 v1.2.5

# mamba list 
Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
_r-mutex                  1.0.1               anacondar_1    conda-forge
argtable2                 2.13              h14c3975_1001    conda-forge
binutils_impl_linux-64    2.36.1               h193b22a_2    conda-forge
bioconductor-biobase      2.50.0            r40hd029910_1    bioconda
bioconductor-biocgenerics 0.36.0            r40hdfd78af_1    bioconda
bioconductor-biocparallel 1.24.1            r40h399db7b_0    bioconda
bioconductor-biomformat   1.18.0            r40hdfd78af_1    bioconda
bioconductor-biostrings   2.58.0            r40hd029910_1    bioconda
bioconductor-dada2        1.18.0            r40h399db7b_1    bioconda
bioconductor-decipher     2.18.1            r40hd029910_0    bioconda
bioconductor-delayedarray 0.16.3            r40hd029910_0    bioconda
bioconductor-genomeinfodb 1.26.4            r40hdfd78af_0    bioconda
bioconductor-genomeinfodbdata 1.2.4             r40hdfd78af_2    bioconda
bioconductor-genomicalignments 1.26.0            r40hd029910_1    bioconda
bioconductor-genomicranges 1.42.0            r40hd029910_1    bioconda
bioconductor-iranges      2.24.1            r40hd029910_0    bioconda
bioconductor-matrixgenerics 1.2.1             r40hdfd78af_0    bioconda
bioconductor-microbiome   1.12.0            r40hdfd78af_1    bioconda
bioconductor-multtest     2.46.0            r40hd029910_1    bioconda
bioconductor-phyloseq     1.34.0            r40hdfd78af_1    bioconda
bioconductor-rhdf5        2.34.0            r40h399db7b_1    bioconda
bioconductor-rhdf5filters 1.2.0             r40h399db7b_1    bioconda
bioconductor-rhdf5lib     1.12.1            r40hd029910_0    bioconda
bioconductor-rhtslib      1.22.0            r40hd029910_1    bioconda
bioconductor-rsamtools    2.6.0             r40h399db7b_1    bioconda
bioconductor-s4vectors    0.28.1            r40hd029910_0    bioconda
bioconductor-shortread    1.48.0            r40h399db7b_1    bioconda
bioconductor-summarizedexperiment 1.20.0            r40hdfd78af_1    bioconda
bioconductor-xvector      0.30.0            r40hd029910_1    bioconda
bioconductor-zlibbioc     1.36.0            r40hd029910_1    bioconda
biom-format               2.1.10          py310h96516ba_1    conda-forge
bwidget                   1.9.14               ha770c72_1    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2022.6.15            ha878542_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cairo                     1.16.0            ha61ee94_1011    conda-forge
click                     8.1.3           py310hff52083_0    conda-forge
clustalo                  1.2.4                h87f3376_5    bioconda
commonmark                0.9.1                      py_0    conda-forge
curl                      7.83.1               h2283fc2_0    conda-forge
cutadapt                  4.1             py310h1425a21_1    bioconda
dadaist2                  1.2.5                hdfd78af_0    bioconda
dataclasses               0.8                pyhc8e2a94_3    conda-forge
dnaio                     0.9.1           py310h1425a21_1    bioconda
expat                     2.4.8                h27087fc_0    conda-forge
fastp                     0.23.2               hb7a2d85_2    bioconda
fasttree                  2.1.11               hec16e2b_1    bioconda
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.0               h8e229c2_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.10.4               hca18f0e_2    conda-forge
fribidi                   1.0.10               h36c2ea0_0    conda-forge
future                    0.18.2          py310hff52083_5    conda-forge
gcc_impl_linux-64         12.1.0              hea43390_16    conda-forge
gettext                   0.19.8.1          h73d1719_1008    conda-forge
gfortran_impl_linux-64    12.1.0              h1db8e46_16    conda-forge
glpk                      5.0                  h445213a_0    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
graphite2                 1.3.13            h58526e2_1001    conda-forge
gsl                       2.7                  he838d99_0    conda-forge
gxx_impl_linux-64         12.1.0              hea43390_16    conda-forge
h5py                      3.7.0           nompi_py310h06dffec_100    conda-forge
harfbuzz                  5.1.0                hf9f4e7c_0    conda-forge
hdf5                      1.12.1          nompi_h4df4325_104    conda-forge
icu                       70.1                 h27087fc_0    conda-forge
isa-l                     2.30.0               ha770c72_4    conda-forge
jpeg                      9e                   h166bdaf_2    conda-forge
kernel-headers_linux-64   2.6.32              he073ed8_15    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.19.3               h08a2579_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
lerc                      3.0                  h9c3ff4c_0    conda-forge
libblas                   3.9.0           16_linux64_openblas    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libcurl                   7.83.1               h2283fc2_0    conda-forge
libdeflate                1.10                 h7f98852_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-devel_linux-64     12.1.0              h1ec3361_16    conda-forge
libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
libgfortran-ng            12.1.0              h69a702a_16    conda-forge
libgfortran5              12.1.0              hdcd56e2_16    conda-forge
libglib                   2.72.1               h2d90d5f_0    conda-forge
libgomp                   12.1.0              h8d9b700_16    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0           16_linux64_openblas    conda-forge
libnghttp2                1.47.0               he49606f_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.21          pthreads_h78a6416_0    conda-forge
libpng                    1.6.37               h753d276_3    conda-forge
libsanitizer              12.1.0              ha89aaad_16    conda-forge
libssh2                   1.10.0               ha35d2d1_2    conda-forge
libstdcxx-devel_linux-64  12.1.0              h1ec3361_16    conda-forge
libstdcxx-ng              12.1.0              ha89aaad_16    conda-forge
libtiff                   4.4.0                h0fcbabc_0    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libwebp-base              1.2.4                h166bdaf_0    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxml2                   2.9.14               h22db469_3    conda-forge
libzip                    1.9.2                hc929e4a_0    conda-forge
libzlib                   1.2.12               h166bdaf_2    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
make                      4.3                  hd18ef5c_1    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
numpy                     1.23.1          py310h53a5b5f_0    conda-forge
openssl                   3.0.5                h166bdaf_1    conda-forge
pandas                    1.4.3           py310h769672d_0    conda-forge
pango                     1.50.8               hc4f8a73_1    conda-forge
pbzip2                    1.1.13                        0    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
pcre2                     10.37                h032f7d1_0    conda-forge
perl                      5.32.1          2_h7f98852_perl5    conda-forge
perl-capture-tiny         0.48            pl5321ha770c72_1    conda-forge
perl-carp                 1.50            pl5321hd8ed1ab_0    conda-forge
perl-exporter             5.74            pl5321hd8ed1ab_0    conda-forge
perl-extutils-makemaker   7.64            pl5321hd8ed1ab_0    conda-forge
perl-fastx-reader         1.5.0           pl5321hdfd78af_0    bioconda
pigz                      2.6                  h27826a3_0    conda-forge
pip                       22.2.2             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pygments                  2.12.0             pyhd8ed1ab_0    conda-forge
python                    3.10.5          ha86cf86_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-isal               1.0.1           py310h5764c6d_0    conda-forge
python_abi                3.10                    2_cp310    conda-forge
pytz                      2022.1             pyhd8ed1ab_0    conda-forge
qax                       0.9.6                hac521b0_1    bioconda
r-ade4                    1.7_19            r40h0154571_0    conda-forge
r-ape                     5.6_2             r40h43535f1_0    conda-forge
r-assertthat              0.2.1             r40hc72bb7e_2    conda-forge
r-backports               1.4.1             r40hcfec24a_0    conda-forge
r-base                    4.0.5                ha8c3e7c_7    conda-forge
r-bh                      1.78.0_0          r40hc72bb7e_0    conda-forge
r-bit                     4.0.4             r40hcfec24a_0    conda-forge
r-bit64                   4.0.5             r40hcfec24a_0    conda-forge
r-bitops                  1.0_7             r40h06615bd_0    conda-forge
r-blob                    1.2.3             r40hc72bb7e_0    conda-forge
r-brio                    1.1.3             r40hcfec24a_0    conda-forge
r-cachem                  1.0.6             r40hcfec24a_0    conda-forge
r-callr                   3.7.1             r40hc72bb7e_0    conda-forge
r-cli                     3.3.0             r40h7525677_0    conda-forge
r-cluster                 2.1.3             r40h8da6f51_0    conda-forge
r-codetools               0.2_18            r40hc72bb7e_0    conda-forge
r-colorspace              2.0_3             r40h06615bd_0    conda-forge
r-crayon                  1.5.1             r40hc72bb7e_0    conda-forge
r-data.table              1.14.2            r40hcfec24a_0    conda-forge
r-dbi                     1.1.3             r40hc72bb7e_0    conda-forge
r-deldir                  1.0_6             r40h8da6f51_0    conda-forge
r-desc                    1.4.1             r40hc72bb7e_0    conda-forge
r-diffobj                 0.3.5             r40hcfec24a_0    conda-forge
r-digest                  0.6.29            r40h03ef668_0    conda-forge
r-dplyr                   1.0.9             r40h7525677_0    conda-forge
r-ellipsis                0.3.2             r40hcfec24a_0    conda-forge
r-evaluate                0.16              r40hc72bb7e_0    conda-forge
r-fansi                   1.0.3             r40h06615bd_0    conda-forge
r-farver                  2.1.1             r40h7525677_0    conda-forge
r-fastmap                 1.1.0             r40h03ef668_0    conda-forge
r-foreach                 1.5.2             r40hc72bb7e_0    conda-forge
r-formatr                 1.12              r40hc72bb7e_0    conda-forge
r-fs                      1.5.2             r40h7525677_1    conda-forge
r-futile.logger           1.4.3           r40hc72bb7e_1003    conda-forge
r-futile.options          1.0.1           r40hc72bb7e_1002    conda-forge
r-generics                0.1.3             r40hc72bb7e_0    conda-forge
r-ggplot2                 3.3.6             r40hc72bb7e_0    conda-forge
r-glue                    1.6.2             r40h06615bd_0    conda-forge
r-gtable                  0.3.0             r40hc72bb7e_3    conda-forge
r-hms                     1.1.1             r40hc72bb7e_0    conda-forge
r-hwriter                 1.3.2.1           r40hc72bb7e_0    conda-forge
r-igraph                  1.3.4             r40hb34fc8a_0    conda-forge
r-interp                  1.1_3             r40h7525677_0    conda-forge
r-isoband                 0.2.5             r40h03ef668_0    conda-forge
r-iterators               1.0.14            r40hc72bb7e_0    conda-forge
r-jpeg                    0.1_9             r40hcfec24a_0    conda-forge
r-jsonlite                1.8.0             r40h06615bd_0    conda-forge
r-labeling                0.4.2             r40hc72bb7e_1    conda-forge
r-lambda.r                1.2.4             r40hc72bb7e_1    conda-forge
r-lattice                 0.20_45           r40hcfec24a_0    conda-forge
r-latticeextra            0.6_30            r40hc72bb7e_0    conda-forge
r-lifecycle               1.0.1             r40hc72bb7e_0    conda-forge
r-magrittr                2.0.3             r40h06615bd_0    conda-forge
r-mass                    7.3_58.1          r40h06615bd_0    conda-forge
r-matrix                  1.3_2             r40he454529_0    conda-forge
r-matrixstats             0.62.0            r40h06615bd_0    conda-forge
r-memoise                 2.0.1             r40hc72bb7e_0    conda-forge
r-mgcv                    1.8_40            r40h0154571_0    conda-forge
r-munsell                 0.5.0           r40hc72bb7e_1004    conda-forge
r-nlme                    3.1_159           r40h8da6f51_0    conda-forge
r-permute                 0.9_7             r40hc72bb7e_0    conda-forge
r-pillar                  1.8.0             r40hc72bb7e_0    conda-forge
r-pixmap                  0.4_12            r40hc72bb7e_0    conda-forge
r-pkgconfig               2.0.3             r40hc72bb7e_1    conda-forge
r-pkgload                 1.3.0             r40hc72bb7e_0    conda-forge
r-plogr                   0.2.0           r40hc72bb7e_1003    conda-forge
r-plyr                    1.8.7             r40h7525677_0    conda-forge
r-png                     0.1_7           r40hcfec24a_1004    conda-forge
r-praise                  1.0.0           r40hc72bb7e_1005    conda-forge
r-prettyunits             1.1.1             r40hc72bb7e_1    conda-forge
r-processx                3.7.0             r40h06615bd_0    conda-forge
r-progress                1.2.2             r40hc72bb7e_2    conda-forge
r-ps                      1.7.1             r40h06615bd_0    conda-forge
r-purrr                   0.3.4             r40hcfec24a_1    conda-forge
r-r6                      2.5.1             r40hc72bb7e_0    conda-forge
r-rcolorbrewer            1.1_3             r40h785f33e_0    conda-forge
r-rcpp                    1.0.9             r40h7525677_0    conda-forge
r-rcppeigen               0.3.3.9.2         r40h43535f1_0    conda-forge
r-rcppparallel            5.1.5             r40h7525677_0    conda-forge
r-rcurl                   1.98_1.8          r40h06615bd_0    conda-forge
r-rematch2                2.1.2             r40hc72bb7e_1    conda-forge
r-reshape2                1.4.4             r40h03ef668_1    conda-forge
r-rlang                   1.0.4             r40h7525677_0    conda-forge
r-rprojroot               2.0.3             r40hc72bb7e_0    conda-forge
r-rsqlite                 2.2.8             r40h03ef668_0    conda-forge
r-rtsne                   0.16              r40h37cf8d7_0    conda-forge
r-scales                  1.2.0             r40hc72bb7e_0    conda-forge
r-snow                    0.4_4             r40hc72bb7e_0    conda-forge
r-sp                      1.5_0             r40h06615bd_0    conda-forge
r-stringi                 1.7.8             r40h30a9eb7_0    conda-forge
r-stringr                 1.4.0             r40hc72bb7e_2    conda-forge
r-survival                3.4_0             r40h06615bd_0    conda-forge
r-testthat                3.1.4             r40h7525677_0    conda-forge
r-tibble                  3.1.8             r40h06615bd_0    conda-forge
r-tidyr                   1.2.0             r40h03ef668_0    conda-forge
r-tidyselect              1.1.2             r40hc72bb7e_0    conda-forge
r-utf8                    1.2.2             r40hcfec24a_0    conda-forge
r-vctrs                   0.4.1             r40h7525677_0    conda-forge
r-vegan                   2.6_2             r40he5c027b_0    conda-forge
r-viridislite             0.4.0             r40hc72bb7e_0    conda-forge
r-waldo                   0.4.0             r40hc72bb7e_0    conda-forge
r-withr                   2.5.0             r40hc72bb7e_0    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
rich                      12.5.1             pyhd8ed1ab_0    conda-forge
scipy                     1.9.0           py310hdfbd76f_0    conda-forge
sed                       4.8                  he412f7d_0    conda-forge
seqfu                     1.14.0               hbd632db_1    bioconda
setuptools                63.4.3          py310hff52083_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.39.2               h4ff8645_0    conda-forge
sysroot_linux-64          2.12                he073ed8_15    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tktable                   2.10                 hb7b940f_3    conda-forge
typing_extensions         4.3.0              pyha770c72_0    conda-forge
tzdata                    2022a                h191b570_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xopen                     1.5.0           py310hff52083_0    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.7.2                h7f98852_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-libxt                1.2.1                h7f98852_2    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zip                       3.0                  h7f98852_1    conda-forge
zlib                      1.2.12               h166bdaf_2    conda-forge
zstd                      1.5.2                h8a70e8d_3    conda-forge

## running the command
dadaist2 -i data/16S/ -o example-output1/ -m metadata.tsv -d silva_nr_v138_train_set.fa.gz --verbose -trunc-len-1 255 -trunc-len-2 224 -maxee1 2 -maxee1 2 -s1 16 -s2 24 --max-loss 0.05 --save-rds

Error

2022-08-12 13:14:22] DADA2 Finished.
[2022-08-12 13:14:22] Converting dada2 taxonomy output: /tmp/dadaist2_S5cnK8/taxonomy.tsv
[2022-08-12 13:14:22] 38 representative sequences found.
[2022-08-12 13:14:22] DADA2 filtered 28.8127% from total 16104 to 4640
[2022-08-12 13:14:22] Multiple sequence alignment and tree generation
[2022-08-12 13:14:23] Feature tree generated
[2022-08-12 13:14:23] Exporting MicrobiomeAnalyst
[2022-08-12 13:14:29] PhyloSeq file not generated: path_to/trial_reads/data/microbial/toy/example-output1/R/phyloseq.rds
[2022-08-12 13:14:29] Diagnostics: ╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ dadaist2-phyloseqMake 1.2.5                                                                                                                                                                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────── Dadaist2: path_to/data/microbial/toy/example-output1 ───────────────────────────────────────────────────╮
│                                                                                                                                                                                                      │
│ path:         path_totrial_reads/data/microbial/toy/example-output1                                                                                                  │
│ version:       1.2.5                                                                                                                                                                                 │
│ valid:         Yes                                                                                                                                                                                   │
│ num_otus:      38                                                                                                                                                                                    │
│ num_samples:   3                                                                                                                                                                                     │
│ base_files:    rep-seqs.fasta, feature-table.tsv, metadata.tsv, rep-seqs.tree                                                                                                                        │
│ has_phyloseq:  -                                                                                                                                                                                     │
│ has_rhea:      -                                                                                                                                                                                     │
│ has_analyst:   Yes path_to/trial_reads/data/microbial/toy/example-output1/MicrobiomeAnalyst                                                                            │
│                                                                                                                                                                                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
[13:14:24] Input directory "path_to/trial_reads/data/microbial/toy/example-output1/" created with Dadaist2 1.2.5                                  dadaist2-phyloseqMake:55
           MicrobiomeAnalyst directory found: path_to/data/microbial/toy/example-output1/MicrobiomeAnalyst                            dadaist2-phyloseqMake:56
ERROR: R script failed with exit code 1
R version 4.0.5 (2021-03-31) 
 * Input:  path_to/trial_reads/data/microbial/toy/example-output1/ 
Error: package or namespace load failed for ‘phyloseq’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object 'path_to/miniconda3/envs/dadaist/lib/R/library/rhdf5/libs/rhdf5.so':
  libcrypto.so.1.1: cannot open shared object file: No such file or directory
Execution halted

**Comment by telatin** [comment]
Hello @sudeep71,
Sorry for the late reply, I missed this.
what were you using?
